import { Router } from 'express';
import healthRoutes from './health.routes.js';
import authRoutes from './auth.routes.js';
import sellerRoutes from './seller.routes.js';
import storeRoutes from './store.routes.js';
import categoryRoutes from './category.routes.js';
import productRoutes from './product.routes.js';
import batchRoutes from './batch.routes.js';
import inventoryRoutes from './inventory.routes.js';
import pricingRoutes from './pricing.routes.js';
import expiryRoutes from './expiry.routes.js';
import marketplaceRoutes from './marketplace.routes.js';
import wishlistRoutes from './wishlist.routes.js';
import cartRoutes from './cart.routes.js';
import orderRoutes from './order.routes.js';
import paymentRoutes from './payment.routes.js';
import qrRoutes from './qr.routes.js';
import notificationRoutes from './notification.routes.js';
import adminRoutes from './admin.routes.js';
import analyticsRoutes from './analytics.routes.js';
import billingRoutes from './billing.routes.js';
import complaintRoutes from './complaint.routes.js';

const router = Router();

router.use('/health', healthRoutes);
router.use('/auth', authRoutes);
router.use('/sellers', sellerRoutes);
router.use('/stores', storeRoutes);
router.use('/categories', categoryRoutes);
router.use('/products', productRoutes);
router.use('/batches', batchRoutes);
router.use('/inventory', inventoryRoutes);
router.use('/pricing', pricingRoutes);
router.use('/expiry', expiryRoutes);
router.use('/marketplace', marketplaceRoutes);
router.use('/wishlist', wishlistRoutes);
router.use('/cart', cartRoutes);
router.use('/orders', orderRoutes);
router.use('/payments', paymentRoutes);
router.use('/qr', qrRoutes);
router.use('/notifications', notificationRoutes);
router.use('/admin', adminRoutes);
router.use('/analytics', analyticsRoutes);
router.use('/billing', billingRoutes);
router.use('/complaints', complaintRoutes);

export default router;
